#### Tarea 11 - Método Gauss-Jacobi y Gauss- Seidel

Nombre: Carolay Pillajo

Curso: GR1CC

1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por medio de $x(𝟎) = 0:$ 

a)

\begin{cases}
3x_1 - x_2 + x_3 = 1 \\
3x_1 + 6x_2 + 2x_3 = 0 \\
3x_1 + 3x_2 + 7x_3 = 4
\end{cases}


In [40]:
import numpy as np

def jacobi(A, b):
    n = len(b)
    x = np.zeros(n)  

    print("Método de Jacobi")
    print("x(0) =", x)

    for k in range(1, 3):  
        x_new = np.zeros(n)

        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x_new[i] = (b[i] - suma) / A[i][i]

        print(f"x({k}) =", x_new)
        x = x_new.copy()

    return x

In [41]:
A = np.array([
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
], dtype=float)

b = np.array([1, 0, 4], dtype=float)

jacobi(A, b)

Método de Jacobi
x(0) = [0. 0. 0.]
x(1) = [0.33333333 0.         0.57142857]
x(2) = [ 0.14285714 -0.35714286  0.42857143]


array([ 0.14285714, -0.35714286,  0.42857143])

b)

\begin{cases}
10x_1 - x_2 = 9 \\
- x_1 + 10x_2 - 2x_3 = 7 \\
- 2x_2 + 10x_3 = 6
\end{cases}

In [42]:
A = np.array([
    [10, -1,  0],
    [-1, 10, -2],
    [0, -2, 10]
], dtype=float)

b = np.array([9, 7, 6], dtype=float)

jacobi(A, b)

Método de Jacobi
x(0) = [0. 0. 0.]
x(1) = [0.9 0.7 0.6]
x(2) = [0.97 0.91 0.74]


array([0.97, 0.91, 0.74])

c)

\begin{cases}
10x_1 + 5x_2 = 6 \\
5x_1 + 10x_2 - 4x_3 = 25 \\
-4x_2 + 8x_3 - x_4 = -11 \\
- x_3 + 5x_4 = -11
\end{cases}

In [43]:
A = np.array([
    [10,  5,  0,  0],
    [5,  10, -4,  0],
    [0,  -4,  8, -1],
    [0,   0, -1,  5]
], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)

jacobi(A, b)

Método de Jacobi
x(0) = [0. 0. 0. 0.]
x(1) = [ 0.6    2.5   -1.375 -2.2  ]
x(2) = [-0.65   1.65  -0.4   -2.475]


array([-0.65 ,  1.65 , -0.4  , -2.475])

d)

\begin{cases}
4x_1 + x_2 + x_3 + x_5 = 6 \\
- x_1 - 3x_2 + x_3 + x_4 = 6 \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6 \\
- x_1 - x_2 - x_3 + 4x_4 = 6 \\
2x_2 - x_3 + x_4 + 4x_5 = 6
\end{cases}

In [44]:
A = np.array([
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)

jacobi(A, b)


Método de Jacobi
x(0) = [0. 0. 0. 0. 0.]
x(1) = [ 1.5 -2.   1.2  1.5  1.5]
x(2) = [ 1.325 -1.6    1.6    1.675  2.425]


array([ 1.325, -1.6  ,  1.6  ,  1.675,  2.425])

2. Repita el ejercicio 1 usando el método de Gauss -Siedel . 

a)

\begin{cases}
3x_1 - x_2 + x_3 = 1 \\
3x_1 + 6x_2 + 2x_3 = 0 \\
3x_1 + 3x_2 + 7x_3 = 4
\end{cases}

In [45]:
import numpy as np

def gauss_seidel(A, b):
    n = len(b)
    x = np.zeros(n)  

    print("Método de Gauss-Seidel")
    print("x(0) =", x)

    for k in range(1, 3):  
        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x[i] = (b[i] - suma) / A[i][i]

        print(f"x({k}) =", x)

    return x

In [46]:
A = np.array([
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
], dtype=float)

b = np.array([1, 0, 4], dtype=float)

gauss_seidel(A, b)

Método de Gauss-Seidel
x(0) = [0. 0. 0.]
x(1) = [ 0.33333333 -0.16666667  0.5       ]
x(2) = [ 0.11111111 -0.22222222  0.61904762]


array([ 0.11111111, -0.22222222,  0.61904762])

b)

\begin{cases}
10x_1 - x_2 = 9 \\
- x_1 + 10x_2 - 2x_3 = 7 \\
- 2x_2 + 10x_3 = 6
\end{cases}

In [47]:
A = np.array([
    [10, -1,  0],
    [-1, 10, -2],
    [0, -2, 10]
], dtype=float)

b = np.array([9, 7, 6], dtype=float)

gauss_seidel(A, b)

Método de Gauss-Seidel
x(0) = [0. 0. 0.]
x(1) = [0.9   0.79  0.758]
x(2) = [0.979  0.9495 0.7899]


array([0.979 , 0.9495, 0.7899])

c)

\begin{cases}
10x_1 + 5x_2 = 6 \\
5x_1 + 10x_2 - 4x_3 = 25 \\
-4x_2 + 8x_3 - x_4 = -11 \\
- x_3 + 5x_4 = -11
\end{cases}

In [48]:
A = np.array([
    [10,  5,  0,  0],
    [5,  10, -4,  0],
    [0,  -4,  8, -1],
    [0,   0, -1,  5]
], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)

gauss_seidel(A, b)

Método de Gauss-Seidel
x(0) = [0. 0. 0. 0.]
x(1) = [ 0.6    2.2   -0.275 -2.255]
x(2) = [-0.5       2.64     -0.336875 -2.267375]


array([-0.5     ,  2.64    , -0.336875, -2.267375])

d)

\begin{cases}
4x_1 + x_2 + x_3 + x_5 = 6 \\
- x_1 - 3x_2 + x_3 + x_4 = 6 \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6 \\
- x_1 - x_2 - x_3 + 4x_4 = 6 \\
2x_2 - x_3 + x_4 + 4x_5 = 6
\end{cases}

In [49]:
A = np.array([
    [10,  5,  0,  0],
    [5,  10, -4,  0],
    [0,  -4,  8, -1],
    [0,   0, -1,  5]
], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)

gauss_seidel(A, b)

Método de Gauss-Seidel
x(0) = [0. 0. 0. 0.]
x(1) = [ 0.6    2.2   -0.275 -2.255]
x(2) = [-0.5       2.64     -0.336875 -2.267375]


array([-0.5     ,  2.64    , -0.336875, -2.267375])

3. Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10^{-3}$. 

a)

\begin{cases}
3x_1 - x_2 + x_3 = 1 \\
3x_1 + 6x_2 + 2x_3 = 0 \\
3x_1 + 3x_2 + 7x_3 = 4
\end{cases}

In [50]:
import numpy as np

def jacobi(A, b, tol=1e-3, max_iter=100):
    n = len(b)
    x = np.zeros(n)  # x(0) = 0

    print("Método de Jacobi")
    print("# Iter | x")

    for k in range(1, max_iter + 1):
        x_new = np.zeros(n)

        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x_new[i] = (b[i] - suma) / A[i][i]

        error = np.linalg.norm(x_new - x, ord=np.inf)

        print(f"{k:4d} | {x_new}")

        if error < tol:
            print(f"\nConvergió en {k} iteraciones")
            return x_new

        x = x_new.copy()

    print("\nNo convergió")
    return x

In [51]:
A = np.array([
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
], dtype=float)

b = np.array([1, 0, 4], dtype=float)

jacobi(A, b, tol=1e-3)


Método de Jacobi
# Iter | x
   1 | [0.33333333 0.         0.57142857]
   2 | [ 0.14285714 -0.35714286  0.42857143]
   3 | [ 0.07142857 -0.21428571  0.66326531]
   4 | [ 0.04081633 -0.25680272  0.63265306]
   5 | [ 0.03684807 -0.23129252  0.66399417]
   6 | [ 0.03490444 -0.23975543  0.6547619 ]
   7 | [ 0.03516089 -0.23570619  0.65922185]
   8 | [ 0.03502399 -0.23732106  0.65737656]
   9 | [ 0.03510079 -0.23663751  0.65812732]

Convergió en 9 iteraciones


array([ 0.03510079, -0.23663751,  0.65812732])

b)

\begin{cases}
10x_1 - x_2 = 9 \\
- x_1 + 10x_2 - 2x_3 = 7 \\
- 2x_2 + 10x_3 = 6
\end{cases}

In [52]:
A = np.array([
    [10, -1,  0],
    [-1, 10, -2],
    [0, -2, 10]
], dtype=float)

b = np.array([9, 7, 6], dtype=float)

jacobi(A, b, tol=1e-3)


Método de Jacobi
# Iter | x
   1 | [0.9 0.7 0.6]
   2 | [0.97 0.91 0.74]
   3 | [0.991 0.945 0.782]
   4 | [0.9945 0.9555 0.789 ]
   5 | [0.99555 0.95725 0.7911 ]
   6 | [0.995725 0.957775 0.79145 ]

Convergió en 6 iteraciones


array([0.995725, 0.957775, 0.79145 ])

c)

\begin{cases}
10x_1 + 5x_2 = 6 \\
5x_1 + 10x_2 - 4x_3 = 25 \\
-4x_2 + 8x_3 - x_4 = -11 \\
- x_3 + 5x_4 = -11
\end{cases}

In [53]:
A = np.array([
    [10,  5,  0,  0],
    [5,  10, -4,  0],
    [0,  -4,  8, -1],
    [0,   0, -1,  5]
], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)

jacobi(A, b, tol=1e-3)

Método de Jacobi
# Iter | x
   1 | [ 0.6    2.5   -1.375 -2.2  ]
   2 | [-0.65   1.65  -0.4   -2.475]
   3 | [-0.225     2.665    -0.859375 -2.28    ]
   4 | [-0.7325    2.26875  -0.3275   -2.371875]
   5 | [-0.534375    2.73525    -0.53710938 -2.2655    ]
   6 | [-0.767625    2.55234375 -0.2905625  -2.30742188]
   7 | [-0.67617187  2.7675875  -0.38725586 -2.2581125 ]
   8 | [-0.78379375  2.68318359 -0.27347031 -2.27745117]
   9 | [-0.7415918   2.78250875 -0.3180896  -2.25469406]
  10 | [-0.79125437  2.74356006 -0.26558238 -2.26361792]
  11 | [-0.77178003  2.78939423 -0.28617221 -2.25311648]
  12 | [-0.79469712  2.77142113 -0.26194244 -2.25723444]
  13 | [-0.78571057  2.79257158 -0.27144374 -2.25238849]
  14 | [-0.79628579  2.78427779 -0.26026277 -2.25428875]
  15 | [-0.79213889  2.79403779 -0.2646472  -2.25205255]
  16 | [-0.79701889  2.79021057 -0.25948768 -2.25292944]
  17 | [-0.79510528  2.79471438 -0.2615109  -2.25189754]
  18 | [-0.79735719  2.79294828 -0.25913    -2.25230218]
  

array([-0.79710581,  2.79517067, -0.25939578, -2.25179299])

d)

\begin{cases}
4x_1 + x_2 + x_3 + x_5 = 6 \\
- x_1 - 3x_2 + x_3 + x_4 = 6 \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6 \\
- x_1 - x_2 - x_3 + 4x_4 = 6 \\
2x_2 - x_3 + x_4 + 4x_5 = 6
\end{cases}

In [54]:
A = np.array([
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)

jacobi(A, b, tol=1e-3)

Método de Jacobi
# Iter | x
   1 | [ 1.5 -2.   1.2  1.5  1.5]
   2 | [ 1.325 -1.6    1.6    1.675  2.425]
   3 | [ 0.89375 -1.35     1.81     1.83125  2.28125]
   4 | [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]
   5 | [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]
   6 | [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]
   7 | [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]
   8 | [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]
   9 | [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]
  10 | [ 0.78718101 -1.00174151  1.8658388   1.91274157  1.98672138]
  11 | [ 0.78729533 -1.00286688  1.86536849  1.91281957  1.98914507]
  12 | [ 0.78708833 -1.00303576  1.86604817  1.91244923  1.98957067]

Convergió en 12 iteraciones


array([ 0.78708833, -1.00303576,  1.86604817,  1.91244923,  1.98957067])

4. Utilice el método de Gauss-Seidel para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10^{-3}$. 

a)

\begin{cases}
3x_1 - x_2 + x_3 = 1 \\
3x_1 + 6x_2 + 2x_3 = 0 \\
3x_1 + 3x_2 + 7x_3 = 4
\end{cases}

In [55]:
import numpy as np

def gauss_seidel(A, b, tol=1e-3, max_iter=200):
    n = len(b)
    x = np.zeros(n)  # x(0) = 0

    print("Método de Gauss-Seidel")
    print("# Iter | x")

    for k in range(1, max_iter + 1):
        x_old = x.copy()

        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x[i] = (b[i] - suma) / A[i][i]

        error = np.linalg.norm(x - x_old, ord=np.inf)
        print(f"{k:4d} | {x}")

        if error < tol:
            print(f"\nConvergió en {k} iteraciones")
            return x

    print("\nNo convergió")
    return x

In [56]:
A = np.array([
    [3, -1, 1],
    [3,  6, 2],
    [3,  3, 7]
], dtype=float)

b = np.array([1, 0, 4], dtype=float)

gauss_seidel(A, b, tol=1e-3)

Método de Gauss-Seidel
# Iter | x
   1 | [ 0.33333333 -0.16666667  0.5       ]
   2 | [ 0.11111111 -0.22222222  0.61904762]
   3 | [ 0.05291005 -0.23280423  0.64852608]
   4 | [ 0.03955656 -0.23595364  0.65559875]
   5 | [ 0.0361492  -0.23660752  0.65733928]
   6 | [ 0.03535107 -0.23678863  0.65775895]

Convergió en 6 iteraciones


array([ 0.03535107, -0.23678863,  0.65775895])

b)

\begin{cases}
10x_1 - x_2 = 9 \\
- x_1 + 10x_2 - 2x_3 = 7 \\
- 2x_2 + 10x_3 = 6
\end{cases}

In [57]:
A = np.array([
    [10, -1,  0],
    [-1, 10, -2],
    [0, -2, 10]
], dtype=float)

b = np.array([9, 7, 6], dtype=float)

gauss_seidel(A, b, tol=1e-3)

Método de Gauss-Seidel
# Iter | x
   1 | [0.9   0.79  0.758]
   2 | [0.979  0.9495 0.7899]
   3 | [0.99495  0.957475 0.791495]
   4 | [0.9957475  0.95787375 0.79157475]

Convergió en 4 iteraciones


array([0.9957475 , 0.95787375, 0.79157475])

c)

\begin{cases}
10x_1 + 5x_2 = 6 \\
5x_1 + 10x_2 - 4x_3 = 25 \\
-4x_2 + 8x_3 - x_4 = -11 \\
- x_3 + 5x_4 = -11
\end{cases}

In [58]:
A = np.array([
    [10,  5,  0,  0],
    [5,  10, -4,  0],
    [0,  -4,  8, -1],
    [0,   0, -1,  5]
], dtype=float)

b = np.array([6, 25, -11, -11], dtype=float)

gauss_seidel(A, b, tol=1e-3)

Método de Gauss-Seidel
# Iter | x
   1 | [ 0.6    2.2   -0.275 -2.255]
   2 | [-0.5       2.64     -0.336875 -2.267375]
   3 | [-0.72        2.72525    -0.29579687 -2.25915938]
   4 | [-0.762625    2.76299375 -0.27589805 -2.25517961]
   5 | [-0.78149687  2.78038922 -0.26670284 -2.25334057]
   6 | [-0.79019461  2.78841617 -0.26245949 -2.2524919 ]
   7 | [-0.79420808  2.79212025 -0.26050136 -2.25210027]
   8 | [-0.79606012  2.79382952 -0.25959778 -2.25191956]
   9 | [-0.79691476  2.79461827 -0.25918081 -2.25183616]

Convergió en 9 iteraciones


array([-0.79691476,  2.79461827, -0.25918081, -2.25183616])

d)

\begin{cases}
4x_1 + x_2 + x_3 + x_5 = 6 \\
- x_1 - 3x_2 + x_3 + x_4 = 6 \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6 \\
- x_1 - x_2 - x_3 + 4x_4 = 6 \\
2x_2 - x_3 + x_4 + 4x_5 = 6
\end{cases}

In [59]:
A = np.array([
    [ 4,  1,  1,  0,  1],
    [-1, -3,  1,  1,  0],
    [ 2,  1,  5, -1, -1],
    [-1, -1, -1,  4,  0],
    [ 0,  2, -1,  1,  4]
], dtype=float)

b = np.array([6, 6, 6, 6, 6], dtype=float)

gauss_seidel(A, b, tol=1e-3)

Método de Gauss-Seidel
# Iter | x
   1 | [ 1.5     -2.5      1.1      1.525    2.64375]
   2 | [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
   3 | [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]
   4 | [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]
   5 | [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]
   6 | [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]
   7 | [ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976]

Convergió en 7 iteraciones


array([ 0.78668253, -1.00271872,  1.86628339,  1.9125618 ,  1.98978976])

5. El sistema lineal  

\begin{cases}
2x_1 - x_2 + x_3 = -1 \\
2x_1 + 2x_2 + 2x_3 = 4 \\
- x_1 - x_2 + 2x_3 = -5
\end{cases}

tiene la solución $(1, 2, -1)$. 

a) Muestre que el método de Jacobi con $x(0) = 0$ falla al proporcionar una buena aproximación  
después de 25 iteraciones.  

In [60]:
import numpy as np

def jacobi(A, b):
    n = len(b)
    x = np.zeros(n)  # x(0) = 0

    print("Método de Jacobi")
    print("# Iter | x")

    for k in range(1, 26):  
        x_new = np.zeros(n)

        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x_new[i] = (b[i] - suma) / A[i][i]

        print(f"{k:4d} | {x_new}")
        x = x_new.copy()

    return x

In [61]:
A = np.array([
    [ 2, -1,  1],
    [ 2,  2,  2],
    [-1, -1,  2]
], dtype=float)

b = np.array([-1, 4, -5], dtype=float)

jacobi(A, b)

Método de Jacobi
# Iter | x
   1 | [-0.5  2.  -2.5]
   2 | [ 1.75  5.   -1.75]
   3 | [2.875 2.    0.875]
   4 | [ 0.0625 -1.75   -0.0625]
   5 | [-1.34375  2.      -3.34375]
   6 | [ 2.171875  6.6875   -2.171875]
   7 | [3.9296875 2.        1.9296875]
   8 | [-0.46484375 -3.859375    0.46484375]
   9 | [-2.66210938  2.         -4.66210938]
  10 | [ 2.83105469  9.32421875 -2.83105469]
  11 | [5.57763672 2.         3.57763672]
  12 | [-1.28881836 -7.15527344  1.28881836]
  13 | [-4.7220459  2.        -6.7220459]
  14 | [ 3.86102295 13.4440918  -3.86102295]
  15 | [8.15255737 2.         6.15255737]
  16 | [ -2.57627869 -12.30511475   2.57627869]
  17 | [-7.94069672  2.         -9.94069672]
  18 | [ 5.47034836 19.88139343 -5.47034836]
  19 | [12.1758709  2.        10.1758709]
  20 | [ -4.58793545 -20.35174179   4.58793545]
  21 | [-12.96983862   2.         -14.96983862]
  22 | [ 7.98491931 29.93967724 -7.98491931]
  23 | [18.46229827  2.         16.46229827]
  24 | [ -7.73114914 -32.92459

array([-20.82787284,   2.        , -22.82787284])

b) Utilice el método de Gauss-Seidel con $x(0) = 0$:para aproximar la solución para el sistema lineal  
dentro de $10^{−5}$.

In [62]:
import numpy as np

def gauss_seidel(A, b, tol=1e-5, max_iter=500):
    n = len(b)
    x = np.zeros(n)  # x(0) = 0

    print("Método de Gauss-Seidel")
    print("# Iter | x")

    for k in range(1, max_iter + 1):
        x_old = x.copy()

        for i in range(n):
            suma = 0
            for j in range(n):
                if j != i:
                    suma += A[i][j] * x[j]
            x[i] = (b[i] - suma) / A[i][i]

        error = np.linalg.norm(x - x_old, ord=np.inf)
        print(f"{k:4d} | {x}")

        if error < tol:
            print(f"\nConvergió en {k} iteraciones")
            return x

    print("\nNo convergió")
    return x

In [63]:
A = np.array([
    [ 2, -1,  1],
    [ 2,  2,  2],
    [-1, -1,  2]
], dtype=float)

b = np.array([-1, 4, -5], dtype=float)

gauss_seidel(A, b, tol=1e-5)

Método de Gauss-Seidel
# Iter | x
   1 | [-0.5  2.5 -1.5]
   2 | [ 1.5   2.   -0.75]
   3 | [ 0.875  1.875 -1.125]
   4 | [ 1.      2.125  -0.9375]
   5 | [ 1.03125  1.90625 -1.03125]
   6 | [ 0.96875   2.0625   -0.984375]
   7 | [ 1.0234375  1.9609375 -1.0078125]
   8 | [ 0.984375    2.0234375  -0.99609375]
   9 | [ 1.00976562  1.98632812 -1.00195312]
  10 | [ 0.99414062  2.0078125  -0.99902344]
  11 | [ 1.00341797  1.99560547 -1.00048828]
  12 | [ 0.99804688  2.00244141 -0.99975586]
  13 | [ 1.00109863  1.99865723 -1.00012207]
  14 | [ 0.99938965  2.00073242 -0.99993896]
  15 | [ 1.00033569  1.99960327 -1.00003052]
  16 | [ 0.99981689  2.00021362 -0.99998474]
  17 | [ 1.00009918  1.99988556 -1.00000763]
  18 | [ 0.99994659  2.00006104 -0.99999619]
  19 | [ 1.00002861  1.99996758 -1.00000191]
  20 | [ 0.99998474  2.00001717 -0.99999905]
  21 | [ 1.00000811  1.99999094 -1.00000048]
  22 | [ 0.99999571  2.00000477 -0.99999976]
  23 | [ 1.00000226  1.9999975  -1.00000012]

Convergió en 2

array([ 1.00000226,  1.9999975 , -1.00000012])

6. El sistema lineal  
 
 \begin{cases}
x_1 - x_3 = 0.2 \\
-\dfrac{1}{2}x_1 + x_2 - \dfrac{1}{4}x_3 = -1.425 \\
x_1 - \dfrac{1}{2}x_2 + x_3 = 2
\end{cases}
 
tiene la solución $(0.9, -0.8, 0.7)$. 

a) ¿La matriz de coeficientes 

A =
\begin{pmatrix}
1 & 0 & -1 \\
-\dfrac{1}{2} & 1 & -\dfrac{1}{4} \\
1 & -\dfrac{1}{2} & 1
\end{pmatrix}

tiene  diagonal  estrictamente dominante?  

In [64]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
])

dominante = True

for i in range(len(A)):
    diag = abs(A[i, i])
    suma = np.sum(np.abs(A[i])) - diag
    print(f"Fila {i+1}: |a_ii| = {diag}, suma restantes = {suma}")

    if diag > suma:
        print("Cumple estricta dominancia\n")
    else:
        print("NO cumple estricta dominancia\n")
        dominante = False

print("¿Matriz estrictamente diagonal dominante?:", dominante)

Fila 1: |a_ii| = 1.0, suma restantes = 1.0
NO cumple estricta dominancia

Fila 2: |a_ii| = 1.0, suma restantes = 0.75
Cumple estricta dominancia

Fila 3: |a_ii| = 1.0, suma restantes = 1.5
NO cumple estricta dominancia

¿Matriz estrictamente diagonal dominante?: False


b) Utilice el método iterativo de Gauss-Seidel para aproximar la solución para el sistema lineal con  
una tolerancia de $10^{22}$ y un máximo de 300 iteraciones.  

In [65]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)

x = np.zeros(3)
tol = 1e22
max_iter = 300

print("Método de Gauss-Seidel")
print("Tolerancia =", tol)
print("Máximo de iteraciones =", max_iter)
print("# Iter | x | Error")

for k in range(1, max_iter + 1):
    x_old = x.copy()

    for i in range(3):
        suma = 0
        for j in range(3):
            if j != i:
                suma += A[i, j] * x[j]
        x[i] = (b[i] - suma) / A[i, i]

    error = np.linalg.norm(x - x_old, ord=np.inf)
    print(f"{k:4d} | {x} | {error}")

    if error < tol:
        print("\nEl método se detiene porque:")
        print(f"El error = {error} es menor que la tolerancia = {tol}")
        print("El máximo de iteraciones NO fue alcanzado")
        break

Método de Gauss-Seidel
Tolerancia = 1e+22
Máximo de iteraciones = 300
# Iter | x | Error
   1 | [ 0.2    -1.325   1.1375] | 1.325

El método se detiene porque:
El error = 1.325 es menor que la tolerancia = 1e+22
El máximo de iteraciones NO fue alcanzado


c) ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?  

\begin{cases}
x_1 - x_3 = 0.2 \\
-\dfrac{1}{2}x_1 + x_2 - \dfrac{1}{4}x_3 = -1.425 \\
x_1 - \dfrac{1}{2}x_2 + x_3 = 2
\end{cases}

In [66]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)

x = np.zeros(3)
tol = 1e22
max_iter = 300

print("Gauss-Seidel - Sistema modificado")
print("Tolerancia =", tol)
print("# Iter | x | Error")

for k in range(1, max_iter + 1):
    x_old = x.copy()

    for i in range(3):
        suma = 0
        for j in range(3):
            if j != i:
                suma += A[i, j] * x[j]
        x[i] = (b[i] - suma) / A[i, i]

    error = np.linalg.norm(x - x_old, ord=np.inf)
    print(f"{k:4d} | {x} | {error}")

    if error < tol:
        print("\nEl comportamiento no cambia")
        print("El sistema es idéntico al anterior")
        print("La tolerancia se cumple en la primera iteración")
        break

Gauss-Seidel - Sistema modificado
Tolerancia = 1e+22
# Iter | x | Error
   1 | [ 0.2    -1.325   1.1375] | 1.325

El comportamiento no cambia
El sistema es idéntico al anterior
La tolerancia se cumple en la primera iteración


7. Repita el ejercicio 11 usando el método de Jacobi. 

In [67]:
import numpy as np

A = np.array([
    [1, 0, -1],
    [-0.5, 1, -0.25],
    [1, -0.5, 1]
], dtype=float)

b = np.array([0.2, -1.425, 2], dtype=float)

x = np.zeros(3)
tol = 1e-3
max_iter = 300

print("Método de Jacobi")
print("# Iter | x | Error")

for k in range(1, max_iter + 1):
    x_old = x.copy()
    x_new = np.zeros(3)

    for i in range(3):
        suma = 0
        for j in range(3):
            if j != i:
                suma += A[i, j] * x_old[j]
        x_new[i] = (b[i] - suma) / A[i, i]

    error = np.linalg.norm(x_new - x_old, ord=np.inf)
    x = x_new

    print(f"{k:4d} | {x} | {error}")

    if error < tol:
        print("\nConvergió en", k, "iteraciones")
        break

Método de Jacobi
# Iter | x | Error
   1 | [ 0.2   -1.425  2.   ] | 2.0
   2 | [ 2.2    -0.825   1.0875] | 2.0
   3 | [ 1.2875   -0.053125 -0.6125  ] | 1.7000000000000002
   4 | [-0.4125    -0.934375   0.6859375] | 1.7000000000000002
   5 | [ 0.8859375  -1.45976563  1.9453125 ] | 1.2984375000000004
   6 | [ 2.1453125  -0.49570312  0.38417969] | 1.5611328125000004
   7 | [ 0.58417969 -0.25629883 -0.39316406] | 1.5611328125000004
   8 | [-0.19316406 -1.23120117  1.2876709 ] | 1.6808349609375006
   9 | [ 1.4876709  -1.19966431  1.57756348] | 1.6808349609375006
  10 | [ 1.77756348 -0.28677368 -0.08750305] | 1.6650665283203132
  11 | [ 0.11249695 -0.55809402  0.07904968] | 1.6650665283203132
  12 | [ 0.27904968 -1.34898911  1.60845604] | 1.5294063568115237
  13 | [ 1.80845604 -0.88336115  1.04645576] | 1.5294063568115237
  14 | [ 1.24645576 -0.25915804 -0.25013661] | 1.2965923786163331
  15 | [-0.05013661 -0.86430627  0.62396522] | 1.2965923786163331
  16 | [ 0.82396522 -1.294077    1.61798

8. Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe mediante la ecuación de Laplace. Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.  

\begin{bmatrix}
4 & -1 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & -1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 0 & 0 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4
\end{bmatrix}

\begin{bmatrix}
w_1 \\
w_2 \\
w_3 \\
w_4 \\
w_5 \\
w_6 \\
w_7 \\
w_8 \\
w_9 \\
w_{10} \\
w_{11} \\
w_{12}
\end{bmatrix}

=

\begin{bmatrix}
220 \\
110 \\
110 \\
220 \\
110 \\
110 \\
110 \\
110 \\
220 \\
110 \\
110 \\
220
\end{bmatrix}

a. ¿La matriz es estrictamente diagonalmente dominante?  

In [68]:
import numpy as np

A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4]
], dtype=float)

dominante = True

print("Verificación de diagonal estrictamente dominante\n")

for i in range(len(A)):
    diag = abs(A[i, i])
    suma = np.sum(np.abs(A[i])) - diag

    print(f"Fila {i+1}")
    print(" |a_ii| =", diag)
    print(" Suma |a_ij|, j≠i =", suma)

    if diag > suma:
        print(" Cumple dominancia estricta\n")
    else:
        print(" NO cumple dominancia estricta\n")
        dominante = False

print("¿La matriz es estrictamente diagonalmente dominante?:", dominante)


Verificación de diagonal estrictamente dominante

Fila 1
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 2
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 3
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 4
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 5
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 6
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 7
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 8
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 9
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 10
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 11
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 2.0
 Cumple dominancia estricta

Fila 12
 |a_ii| = 4.0
 Suma |a_ij|, j≠i = 1.0
 Cumple dominancia estricta

¿La matriz es estrictamente diagonalmente dominante?: True



b. Resuelva el sistema lineal usando el método de Jacobi con $x(0) = 0$ y $TOL = 10^{-2}$. 

In [69]:
import numpy as np

A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4]
], dtype=float)

b = np.array([
    220, 110, 110, 220, 110, 110,
    110, 110, 220, 110, 110, 220
], dtype=float)

x = np.zeros(12)
tol = 1e-2
max_iter = 300

print("Método de Jacobi")
print("#Iter | x | Error\n")

for k in range(1, max_iter + 1):
    x_old = x.copy()
    x_new = np.zeros(12)

    for i in range(12):
        suma = 0
        for j in range(12):
            if j != i:
                suma += A[i, j] * x_old[j]
        x_new[i] = (b[i] - suma) / A[i, i]

    error = np.linalg.norm(x_new - x_old, ord=np.inf)
    x = x_new

    print(f"{k:4d} | {x} | {error}")

    if error < tol:
        print("\nConvergió en", k, "iteraciones")
        break

Método de Jacobi
#Iter | x | Error

   1 | [55.  27.5 27.5 55.  27.5 27.5 27.5 27.5 55.  27.5 27.5 55. ] | 55.0
   2 | [68.75  48.125 48.125 68.75  48.125 48.125 48.125 41.25  68.75  48.125
 55.    61.875] | 27.5
   3 | [79.0625  56.71875 56.71875 79.0625  56.71875 55.      56.71875 51.5625
 80.78125 53.28125 60.15625 67.03125] | 12.03125
   4 | [83.359375  61.4453125 61.4453125 82.9296875 61.4453125 60.15625
 61.875     54.5703125 84.21875   57.1484375 64.453125  68.3203125] | 5.15625
   5 | [85.72265625 63.70117188 63.59375    85.40039062 63.80859375 61.875
 63.91601562 56.82617188 86.58203125 58.22265625 65.63476562 69.28710938] | 2.470703125
   6 | [86.87744141 64.82910156 64.77539062 86.3671875  64.90966797 63.05664062
 65.09765625 57.52441406 87.38769531 59.02832031 66.46728516 69.55566406] | 1.181640625
   7 | [87.43469238 65.41320801 65.29907227 86.95800781 65.49377441 63.47290039
 65.57434082 58.02124023 87.89123535 59.27001953 66.73583984 69.75708008] | 0.5908203125
   8 | [8

c. Repita la parte b) mediante el método de Gauss-Seidel.  

In [70]:
import numpy as np

A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, 4, 0, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 4]
], dtype=float)

b = np.array([
    220, 110, 110, 220, 110, 110,
    110, 110, 220, 110, 110, 220
], dtype=float)

x = np.zeros(12)
tol = 1e-2
max_iter = 300

print("Método de Gauss-Seidel")
print("# Iter | x | Error\n")

for k in range(1, max_iter + 1):
    x_old = x.copy()

    for i in range(12):
        suma = 0
        for j in range(12):
            if j != i:
                suma += A[i, j] * x[j]
        x[i] = (b[i] - suma) / A[i, i]

    error = np.linalg.norm(x - x_old, ord=np.inf)
    print(f"{k:4d} | {x} | {error}")

    if error < tol:
        print("\nConvergió en", k, "iteraciones")
        break


Método de Gauss-Seidel
# Iter | x | Error

   1 | [55.         41.25       37.8125     64.453125   41.25       43.61328125
 37.8125     38.40332031 64.453125   37.10083008 43.61328125 64.27520752] | 64.453125
   2 | [75.625      55.859375   57.578125   80.29785156 55.859375   57.17529297
 57.578125   51.06903076 80.29785156 56.33605957 63.64326477 69.08401489] | 20.625
   3 | [82.9296875  62.62695312 63.23120117 85.10162354 62.62695312 61.54266357
 63.23120117 56.96968079 86.71861649 59.01342392 66.45065784 69.75335598] | 7.3046875
   4 | [86.31347656 64.88616943 64.99694824 86.63490295 64.88616943 63.40114594
 65.40119648 58.10364246 87.96296358 59.46424961 66.92907989 69.8660624 ] | 3.3837890625
   5 | [87.44308472 65.61000824 65.5612278  87.24059343 65.7110703  63.83605897
 65.91850847 58.32507715 88.21189709 59.54778489 67.01948987 69.88694622] | 1.129608154296875
   6 | [87.83026963 65.84787436 65.77211695 87.40204398 65.93719453 63.93178028
 66.0372729  58.36989129 88.26419069 59